package otus202505

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.http.request.builder.HttpRequestBuilder

object ActionOtus {
  val getMainPage: HttpRequestBuilder = http("open Main Page")
    .get("/webtours")
  val getUserSession: HttpRequestBuilder = http("getUSerSession")
    .get("/cgi-bin/nav.pl?in=home")
    .check(regex("\"\\d+.\\w+\"").saveAs("userSession"))

  val postLogin: HttpRequestBuilder = http("Login")
    .post("/cgi-bin/login.pl")
    .formParam("userSession"," #{userSession}")
    .formParam("username","#{username}")
    .formParam("password","#{password}")
    .formParam("login.x","39")
    .formParam("login.y","13")
    .formParam("JSFormSubmit","off")
    .check(status.is(200))


  val getFlights: HttpRequestBuilder = http("Flights" )
    .get("/cgi-bin/reservations.pl?page=welcome")
    .check(css("option", "value")
      .findRandom(2)
      .saveAs("locations"))
  val postGoToFindFlights: HttpRequestBuilder = http("GoToFindFlights")
    .post("/cgi-bin/reservations.pl")
    .formParam("depart","#{locations(0)}")
    .formParam("departDate","07/28/2025")
    .formParam("arrive","#{locations(1)}")
    .formParam("returnDate","07/29/2025")
    .formParam("numPassengers","1")
    .formParam("seatPref","None")
    .formParam("seatType","Coach")
    .formParam("findFlights.x","38")
    .formParam("findFlights.y","8")
    .formParam(".cgifields","roundtrip")
    .formParam(".cgifields","seatType")
    .formParam(".cgifields","seatPref")
    .check(status.is(200))
    .check(css("input[name=\"outboundFlight\"]", "value")
      .findRandom(1)
      .saveAs("outboundFlight"))

  val postToPaymentDetails: HttpRequestBuilder = http("goToPaymentDetails")
    .post("/cgi-bin/reservations.pl")
    .formParam("outboundFlight","#{outboundFlight(0)}")
    .formParam("numPassengers","1")
    .formParam("advanceDiscount","0")
    .formParam("seatType","Coach")
    .formParam("seatPref","None")
    .formParam("reserveFlights.x","68")
    .formParam("reserveFlights.y","3")
    .check(status.is(200))
    .check(css("input[name=\"firstName\"]", "value").saveAs("firstName"))
    .check(css("input[name=\"lastName\"]", "value")
      .transform(x => x.dropRight(1))
      .saveAs("lastName"))
    .check(css("input[name=\"address1\"]", "value").saveAs("address1"))
    .check(css("input[name=\"address2\"]", "value").saveAs("address2"))

  val postMakePayment: HttpRequestBuilder = http("makePayment")
    .post("/cgi-bin/reservations.pl")
    .formParam("firstName","#{firstName}")
    .formParam("lastName","#{lastName}")
    .formParam("address1","#{address1}")
    .formParam("address2","#{address2}")
    .formParam("pass1","#{firstName} #{lastName}")
    .formParam("numPassengers","1")
    .formParam("seatType","Coach")
    .formParam("seatPref","None")
    .formParam("outboundFlight","#{outboundFlight(0)}")
    .formParam("advanceDiscount","0")
    .formParam("returnFlight","")
    .formParam("JSFormSubmit","off")
    .formParam("buyFlights.x","57")
    .formParam("buyFlights.y","14")
    .formParam(".cgifields","saveCC")
    .check(status.is(200))
}
